### PR TITLE
PR again

### PR DESCRIPTION
**Pull request by Samy-33**

### CODE REVIEW

**Comment by Samy-33** [comment]
Please resolve the conflicts and merge. @arshadsid

**Comment by arshadsid** [comment]
capture

**Comment by arshadsid** [comment]
unable to resolve in the web editor....
should make a PR on your repo?
Or you can sort this?

**Comment by arshadsid** [comment]
@Samy-33 can you add all the pyc files in gitignore?

**Comment by Samy-33** [comment]
Yes, doing that asap. We will be deleting the database too, and while deploying we will have to run both the scripts to feed data.

**Pull request merged**
